# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: PRCheck 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: PR check
    runs-on: macos-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Update pip
      run: python -m pip install --upgrade pip
    
    - name: Build
      run: |
        cd MyLibrary
        swift build -v
        
    - name: Run tests
      with:
        command: |
          cd Fastapi
          pip install "fastapi[all]"
        start: uvicorn app.main:app --reload
        build: |
          cd ..
          pwd
          swift test -v
